// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKih2rn522tBaNkZIE9q7Q_MelfTh1t5Q',
    appId: '1:789421621735:web:75ed603c933c64e52b3d42',
    messagingSenderId: '789421621735',
    projectId: 'skill-swap-1c92c',
    authDomain: 'skill-swap-1c92c.firebaseapp.com',
    storageBucket: 'skill-swap-1c92c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCt3AONr3hAZZI4oH_2o_qKm8JaH9sMYA',
    appId: '1:789421621735:android:197daac9d1ed02f12b3d42',
    messagingSenderId: '789421621735',
    projectId: 'skill-swap-1c92c',
    storageBucket: 'skill-swap-1c92c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgaV6eF8_Xxl1_5rrUv10Ur3fB_siRX7M',
    appId: '1:789421621735:ios:fc73ed13f48788e22b3d42',
    messagingSenderId: '789421621735',
    projectId: 'skill-swap-1c92c',
    storageBucket: 'skill-swap-1c92c.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );
}
